baseurl = "https://powersj.github.io/ocv/"
languageCode = "en-us"
title = "Online Course Visualizer"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Joshua Powers"
	description = "Seeing the paths online education takes"


	# Navigation
	[params.navigation]
		brand = "Online Course Visualizer"

		[params.navigation.links]
			about      = "Objective"
			services   = "Features"
			portfolio  = "Demos"
			contact    = "Download"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Seeing the paths online education can take"
		subtitle   = "Help educators and students to visualize the course structure."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Objective"
		description = "The goal of this project is to create visualizations of online educational courses. This will help educators understand the methods they are using to teach and assess students. The project helps students understand the course and how it is structured. It is specifically targeted for students and teachers using MOOC platforms, like edX."
		buttonText  = "Check out the demos below!"


	# Service section
	[params.services]
		headline = "Features"

        [[params.services.list]]
            icon = "fa-graduation-cap"
            title = "Entire Course"
            description = "See an entire course in one image!"

        [[params.services.list]]
			icon = "fa-gears"
			title = "Automated"
			description = "Connect to MOOCs and have the visualization build!"

		[[params.services.list]]
            icon = "fa-sitemap"
            title = "Interactive"
            description = "Zoom in and out, move around, expand and hide objects!"

        [[params.services.list]]
            icon = "fa-database"
            title = "Details"
            description = "Get additional details like video lengths and problem set features!"


	# Portfolio section
	[params.portfolio]
		headline = "Demos"

	    # Portfolio modals
		[params.portfolio.modal]
	        client = "Client"
	        date = "Date"
	        category = "Category"
	        buttonText = "Go Back"

    # Aside section
	[params.aside]
		headline = "Click the images above for demos of the visualizations!"

	# Contact section
	[params.contact]
		headline = "Download"
		description = "Download, extend, enhance, and share ideas on how to enhance!"

		[params.contact.button]
			text = "Download Here"
			link = "https://github.com/powersj/ocv"
